# Generated by Django 5.1.1 on 2024-10-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_store_description_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
