# Generated by Django 5.1.1 on 2024-10-16 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupon', '0001_initial'),
        ('Store', '0004_alter_product_category_alter_product_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='cart',
        ),
        migrations.AddField(
            model_name='coupon',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Store.store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
