# Generated by Django 5.1.1 on 2024-10-16 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupon', '0002_remove_coupon_cart_coupon_store_alter_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2024, 10, 31)),
        ),
    ]
