# Generated by Django 5.1.1 on 2024-10-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupon', '0003_alter_coupon_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
