# Generated by Django 5.1.1 on 2024-10-16 01:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupon', '0004_alter_coupon_code'),
        ('Store', '0004_alter_product_category_alter_product_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(fields=('code', 'store'), name='unique_coupon_per_store'),
        ),
    ]
