# Generated by Django 5.1.1 on 2024-10-23 22:01

import Coupon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupon', '0006_alter_coupon_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=Coupon.models.default_expiration_date),
        ),
    ]
