# Generated by Django 5.1.1 on 2024-10-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='sub_account_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
