# Generated by Django 5.1.1 on 2024-11-02 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_alter_paymentmethod_sub_account_id'),
        ('Store', '0005_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method', to='Store.store'),
        ),
    ]
