# Generated by Django 5.1.1 on 2024-11-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0007_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='checkout_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
