# Generated by Django 5.1.1 on 2024-11-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0008_transaction_checkout_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='coupon_used',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
