# Generated by Django 5.1.1 on 2024-10-10 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_alter_cartitem_product_alter_cartitem_sub_total'),
        ('Store', '0004_alter_product_category_alter_product_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.product'),
        ),
    ]
