# Generated by Django 5.1.1 on 2024-10-13 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
        ('Store', '0004_alter_product_category_alter_product_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Store.store'),
        ),
    ]
