# Generated by Django 5.1.1 on 2024-10-15 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_cart_checked_out'),
        ('Order', '0003_alter_order_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_by_cart', to='Cart.cart'),
        ),
    ]
